import '@/assets/scss/style.scss'
import AppProvidersWrapper from '@/components/wrapper/AppProvidersWrapper'
import { DEFAULT_PAGE_TITLE } from '@/context/constants'
import { Roboto } from 'next/font/google'
import { ReduxProvider } from './ReduxProvider'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'
const roboto = Roboto({
  display: 'swap',
  style: ['normal', 'italic'],
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
})
export const metadata = {
  title: {
    template: 'Rerp-Project',
    default: DEFAULT_PAGE_TITLE,
  },
   icons: {
    icon: '/favicon.ico',
  },
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={roboto.className} data-bs-theme="dark">
        <div id="__next_splash">
          <ReduxProvider>
           <ToastContainer position="top-center" />
            <AppProvidersWrapper>{children}</AppProvidersWrapper>
          </ReduxProvider>
        </div>
      </body>
    </html>
  )
}
